Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Text.Encodings.Web;
using System.Collections.Generic;
using static P01.NoteReader;
using static P01.Models.Notebook;
using P01.Models;


namespace P01.Controllers
{
    public class CalendarController : Controller
    {
        public IActionResult Index()
        {            
           // ReadAllNotes(0);
            return  View();
        }
        public IActionResult NextPage()
        {
            if(currentNoteId/10 * 10 + 10 < allNotes.Count )
                currentNoteId = currentNoteId/10 * 10 + 10;

            return View("Index");
        }
        public IActionResult PreviousPage()
        {
            if(currentNoteId - 10 >= 0)
                currentNoteId = currentNoteId - 10;
            return View("Index");
        }
        public IActionResult Edit(int id)
        {
            return  View(allNotes.Find(note => note.id == id));
        }
        public IActionResult New()
        {
            allNotes.Add(new Note{
                                    id = allNotes.Count,
                                    title = "New",
                                    text = "Your text",
                                    noteCategories = new List<string>(),
                                    date = DateTime.Now,
                                    isMarkdown = false                               
                                    });
            return  View("Edit",allNotes.Find(note => note.id == allNotes.Count -1));
        }        
        public IActionResult SubmitChanges(int id, string title,string text,DateTime date,bool markdown)
        {
            if(!IsNameUnique(id,title))
            {
                allNotes.Find(note => note.id == id).title = "A file with such a name already exists";
                return View("Edit",allNotes.Find(note => note.id == id));
            }
            Note modifiedNote = allNotes.Find(note => note.id == id);
            modifiedNote.date = date;
            modifiedNote.isMarkdown = markdown;
            
            

            text = "category:"+WriteCategories(modifiedNote.noteCategories)+'\n'+"date:"+date.ToString("MM/dd/yyyy")+'\n'+text;
            if (IsEditing()) // Editing note
            {
                string path = Path.Combine(dirName,modifiedNote.title);
                if(modifiedNote.isMarkdown)
                    path += ".md";                
                System.IO.File.WriteAllText(path,text);
                if(modifiedNote.isMarkdown)
                    System.IO.File.Move(path, Path.Combine(dirName,title+".md"));                
                else
                    System.IO.File.Move(path, Path.Combine(dirName,title));                
                modifiedNote.title = title;
            }
            else //creating new
            {
                modifiedNote.title = title;
                if(modifiedNote.isMarkdown)
                    title += ".md";
                System.IO.File.WriteAllText(Path.Combine(dirName,title),text);        
            }            
            ReadAllNotes(id);
            return View("Index");
        }
        public IActionResult DeleteFile(int id)
        {
            Note modifiedNote = allNotes.Find(note => note.id == id);
            string path = Path.Combine(dirName,modifiedNote.title);
            if(modifiedNote.isMarkdown)
                path += ".md";
            System.IO.File.Delete(path);
            allNotes.RemoveAt(modifiedNote.id);
            displayedNotes.Remove(displayedNotes.Find(note=>note.id == id));
            ReEnumerate();
            return View("Index");
        }
        
        public IActionResult ModifyCategories(int id, string category, string submit)
        {
            if(submit == "Add Category")
                AddCategory(category,id);
            else if(submit == "Remove Category")
                RemoveCategory(category,id);
            return  View("Edit",allNotes.Find(note => note.id == id));
        }
        public IActionResult DeleteFilter()
        {            
            ReadAllNotes(0);
            return View("Index");
        }
        public IActionResult Filter(DateTime from, DateTime to, string category)
        {
            
            if(DateTime.Compare(from,to) > 0)
                return View("Index");
            ReadAllNotes(0); // Update the notes list
            CopyToDisplayNotes();
            fromFilterDate = from;
            toFilterDate = to;
            filteredCategory = category;

            for(var i = displayedNotes.Count -1 ; i>=0; i--)
            {
                var note = displayedNotes.Find(fnote => fnote.id == i);
                //if(!string.IsNullOrEmpty(category))
                if(DateTime.Compare(from, note.date ) > 0 || DateTime.Compare(note.date, to) > 0 || (note.noteCategories.Exists(cat => cat == category) && !string.IsNullOrEmpty(category)))
                    displayedNotes.RemoveAt(note.id);
            }
            return View("Index");
        }
        private bool IsNameUnique(int id, string title)
        {
            if(allNotes.Exists(note => note.title == title))
            {   
                if(allNotes.Find(note => note.id == id).title != title)
                {
                    return false;
                }
                if(allNotes.Find(note => note.id == id).title != title && allNotes.Find(note => note.id == id).isMarkdown)
                    return false;
            }
            return true;
        }
        private bool IsEditing()
        {
            return allNotes.Count == Directory.GetFiles(dirName).Length;
        }
        public static void ReadAllNotes(int recentNoteId)
        {
            ReadFiles(recentNoteId);
            CopyToDisplayNotes();
            fromFilterDate = DateTime.Now;
            toFilterDate = DateTime.Parse("12/12/2030");
            filteredCategory = "";
            
            
            
        }
        private static void AddCategory(string category, int id)
        {
            Note note =  allNotes.Find(snote => snote.id == id);
            if(!note.noteCategories.Contains(category))
                note.noteCategories.Add(category);
            AddCategoryToList(category);
        }
        private void RemoveCategory(string category, int id)
        {
            Note note =  allNotes.Find(snote => snote.id == id);
            if(note.noteCategories.Contains(category))
                note.noteCategories.Remove(category);
        }

        
        private static void CopyToDisplayNotes()
        {
            displayedNotes.Clear();
            foreach(Note note in allNotes)
            {
                displayedNotes.Add(note);
            }
        }
        private static void ReEnumerate()
        {
            int i = 0;
            foreach(Note note in allNotes)
            {
                note.id = i;
                i++;
            }
            i = 0;
            foreach(Note note in displayedNotes)
            {
                note.id = i;
                i++;
            }
        }
        private string WriteCategories(List<String> categories)
        {
            string toRet = "";
            foreach(String cat in categories)
            {
                if(cat!="")
                    toRet += cat + ";";
            }
            if(!String.IsNullOrEmpty(toRet))
                toRet = toRet.Substring(0,toRet.Length -1);
            return toRet;

        }
        
        




        
    }
}

Views/Calendar/Edit.cshtml
@model P01.Models.Note
@{
    String printableDate = @Model.date.Year.ToString() + '-'+@Model.date.Month.ToString("D2") + '-' + @Model.date.Day.ToString("D2");
    
}
<form asp-action="ModifyCategories" asp-controller="Calendar" asp-route-id=@Model.id id ="CatModify"></form>
<div class = "well">
    <form asp-action="SubmitChanges" asp-controller="Calendar" asp-route-id=@Model.id id ="submitaction">
        <div class = "row">
            <div class ="col-sm-1"> Title of the note </div>
            <div class ="col-sm-9">
                
                <input type = "text" style = "width:500px" name = "title" value = "@Model.title">
                
            </div>
            <div class ="col-sm-2">
                <div class = "checkbox">
                    @if(@Model.isMarkdown)
                    {
                        <input type = "checkbox" name = "markdown" value = "true" checked >  
                    }
                    else
                    {
                        <input type = "checkbox" name = "markdown"  value = "true" > 
                    }
                    Markdown
                </div>
            </div>
        </div>
        <textarea name="text" style="width:1000px; height:400px;" form = "submitaction"> @Model.text</textarea>  
        <div class = "row">
            <div class = "col-sm-4">
                <input type = "text" form = "CatModify" name ="category">
                <input type="submit" name = "submit"value="Add Category" form = "CatModify">
                <input type = "submit" name = "submit" value = "Remove Category" form = "CatModify">
            </div>
            <div class = "col-sm-3 "> Category:
                 <select name = "category">
                            
                            @for(int i = 0;i < @Model.noteCategories.Count ;i++)
                            {
                                <option value = "@Notebook.categoriesList.ElementAt(i)">@Model.noteCategories.ElementAt(i) </option>                              
                            }
                           
                </select>
            </div>
            <div class = "col-sm-3"> Date:
                <input type = "date" name = "date" value = @printableDate>
            </div>
            
        </div>
        <hr/>
        <input type="submit" value="Submit">
        
    </form>
    
    <a asp-controller="Calendar" asp-action="Index" type = "button" class="btn btn-default">Cancel</a>
</div>
    
        

Views/Calendar/Index.cshtml
@{
    string fromDate = Notebook.fromFilterDate.Year.ToString() + '-' + Notebook.fromFilterDate.Month.ToString("D2") + '-' + Notebook.fromFilterDate.Day.ToString("D2");
    string toDate = Notebook.toFilterDate.Year.ToString() + '-' + Notebook.toFilterDate.Month.ToString("D2") + '-' + Notebook.toFilterDate.Day.ToString("D2");
    string filterCategory = Notebook.filteredCategory;
    int numberOfPages = (Notebook.displayedNotes.Count - 1)/10 + 1;
    int currentPage = Notebook.currentNoteId /10 +1;
    int displayRange =  currentPage * 10 < Notebook.displayedNotes.Count ? displayRange = currentPage *10 : displayRange = Notebook.displayedNotes.Count;
}
@using  P01.Models;
 <div class = "well">
            <form asp-action="Filter" asp-controller="Calendar">    
                <div class = "row">
                    <div class="col-sm-3">
                        From 
                        <input type="date" name = "from" value = @fromDate> 
                    </div>
                    <div class="col-sm-3">
                        To
                        <input type="date" name = "to" value = @toDate> 
                    </div>
                    <div class="col-sm-3">
                        Category
                       <!-- <input type="text" name = "category" value = @filterCategory>-->
                        <select name = "category">
                            <option value = "@filterCategory" selected>@filterCategory</option>
                            @for(int i = 0;i < Notebook.categoriesList.Count ;i++)
                            {
                                @if(Notebook.categoriesList.ElementAt(i)!= filterCategory)
                                {
                                <option value = "@Notebook.categoriesList.ElementAt(i)">@Notebook.categoriesList.ElementAt(i) </option>
                                }
                            }
                           
                        </select>

                    </div>
                    <div class="col-sm-3">
                        <div class = "btn-group">
                            <input type="submit" value="Filter">
                            <a asp-action="DeleteFilter" asp-controller="Calendar" class="btn btn-default">Delete Filter</a>
                        </div>
                    </div>

            
                </div>
            </form>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Title</th>
                    <th></th>
                    
                </tr>
                </thead>
                <tbody>

                @for(int i = 10 * (currentPage -1);i < @displayRange ;i++)
                {
                    <tr>
                    @{
                    Note note = Notebook.displayedNotes.ElementAt(i);
                    string printableDate =  note.date.Date.ToString("d");
                    int index = note.id;

                    }
                    <td>
                        @Html.DisplayFor(modelItem => printableDate) 
                    </td>
                    <td>@Html.DisplayFor(modelItem => note.title)</td>
                    <td align="right">
                     <a asp-action="Edit" asp-route-id= "@index" class="btn btn-default">Edit</a>
                     <a asp-action="DeleteFile" asp-route-id= "@index" class="btn btn-default">Delete</a>
                    </td>
                </tr>
                }                     
                </tbody>
            </table>

            <hr />
            
            <div class = "row">
                <div class="col-sm-6">
                    <div class="btn-group">
                    <a asp-controller="Calendar" asp-action="New" type = "button" class="btn btn-default">New</a>
                    </div>
                </div>
                <div class="col-sm-2">
                    <a asp-controller="Calendar" asp-action="PreviousPage" type = "button" class="btn btn-default">Previous Page</a>
                </div>
                <div class ="col-sm-2"> Page: @currentPage / @numberOfPages </div>
                <div class="col-sm-2">
                    <a asp-controller="Calendar" asp-action="NextPage" type = "button" class="btn btn-default">Next Page</a>
                </div>

        
            </div>
            <hr />
            


        </div>